apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: microservices-demo
spec:
  template:
    spec:
      nodeSelector:
        node-role: tools
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        args: ["run", "/scripts/script.js"]
        env:
        - name: BASE_URL
          value: "http://petclinic.microservices-demo:8080"
        volumeMounts:
        - name: k6-script
          mountPath: /scripts
      volumes:
      - name: k6-script
        configMap:
          name: k6-script
